'* * * * *': 'tellraw @a "1분 마다 실행"'
'30 * * * *': 'tellraw @a "매시 30분마다 실행"'
'0 0 10 * *': 'tellraw @a "매월 10일 0시 0분에 실행"'
'* * 10 * *': 'tellraw @a "매월 10일에 1분 마다 실행"'
'0 0 10 4 *': 'tellraw @a "매년 4월 10일에 0시 0분에 실행"'
'0 0 * * 1': 'tellraw @a "매주 월요일 0시 0분에 실행 (요일의 숫자표현: 일0 월1 화2 수3 목4 금5 토6)"'
'0 * * * 1': 'tellraw @a "매주 월요일 매시 0분에 실행"'
